confirmOnQuit: true
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>" # alternative/alias of quit
    return: "<esc>" # return to previous menu, will quit if there's nowhere to return
os:
  editPreset: "nvim"
git:
  overrideGpg: true
customCommands:
  - key: "J"
    command: "npm run commit"
    description: "commit with cz-jira"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "C"
    command: "cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
